### PR TITLE
Compliant with WCAG 2.0 AA

### PR DESCRIPTION
**Pull request by RRWD**
1. Added focus with the hover styles (for keyboard a11y)
2. Removed  ::selection pseudo-element (to remove W3C CSS validation error)
3. Changed link colour #e5554e into #C3251D for a contrast ratio of more than 1:4.5 with background #fff background
4. Changed link colour  #e5554e into #ccc for the primary navigation for a contrast ratio of more than 1:4.5 with background #333
5. Made links underlined and not underlined on hover/focus (except for the menus)
6. Added font-sizes in rem, for scalability
7. Gave screen-reader-text a colour and background colour to prevent contrast errors in WAVE

Items 2 and 7 are not really required but will save you support questions if people run their theme through validations software and get errors.

### CODE REVIEW

**Comment by RRWD** [comment]
One item to discuss:
In @cdils Utility Pro the read more link needs the class
```css
.more-link {
	position: relative;
}
```
to prevent conflicts with the body background image.
I dont know if there are other themes that could benefit by this css, maybe add it to the sample theme?

**Comment by cdils** [comment]
I'd suggest adding it since any theme using backstretch scripts could potentially run into the same issue, right?

**Comment by nathanrice** [comment]
@RRWD Do you want to update the PR with `.more-link` code?

**Comment by RRWD** [comment]
@nathanrice @cdils Added more-link position relative to the pull request.

**Pull request merged**
